### PR TITLE
fix(gateway-js): Default variables to an empty object when not provided

### PR DESCRIPTION
**Pull request by cabelitos**
Given a query like this:
```graphql
query MyQuery($arg: Int) {
	myQuery(arg: $arg)
}
```

In case the arg variable is not provided on
the GraphQL request, even though it's not required,
the Gateway would crash, since it would try
to coearce a nullish variables object.
This behavior is not expected,
since the GraphQL-JS library handle this
nicely (see  https://github.com/graphql/graphql-js/blob/d6e760cf7060217bd25fa934bd104ff2400aad96/src/execution/execute.js#L347).
In order to prevent further crashes, a check
was added it will simple provide an empty
object to the getVariablesValues(), just
like the original implementationl.

[1]: https://github.com/graphql/graphql-js/blob/d6e760cf7060217bd25fa934bd104ff2400aad96/src/execution/execute.js#L347

Closes https://github.com/apollographql/federation/issues/196

### CODE REVIEW

**Comment by cabelitos** [comment]
Hey guys, sorry. I did not know that I had to sign the CLA contract. I've just signed.

**Review by barbieri — APPROVED** [review]
lgtm

**Review by bdilly — APPROVED** [review]

**Comment by cabelitos** [comment]
Hey guys, any news on this one?

**Comment by abernix** [comment]
## Reproduction

### Given

```graphql
type Query {
  plan(id: ID): String
}
```

and

```graphql
query Testing($arg:ID) {
  plan(id:$arg)
}
```

### Then

```shell
$ curl 'http://endpoint/graphql' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "query": "query Testing($arg:ID) { plan(id:$arg) }"
  }'
```

### Yields

```json
{"errors":[{"message":"Cannot convert undefined or null to object","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
```

**Review by abernix — APPROVED** [review]
LGTM.  Thanks so much for the contribution/fix!

**Comment by cabelitos** [comment]
@abernix thank you for the support!

**Comment by abernix** [comment]
Released in `@apollo/gateway@0.21.0`!

**Pull request merged**
