### PR TITLE
Docs: bump to gatsby v3

### PR DESCRIPTION
**Pull request by jgarrow**
This PR tests an install of an experimental version of `gatsby-theme-apollo-docs` to see if the upgrade to Gatsby v3 is successful.

### CODE REVIEW

**Comment by trevor-scheer** [comment]
Awesome! If we do land this, just note that we land the same changes over on the `version-0.x` branch. Thanks @jgarrow!

**Comment by trevor-scheer** [comment]
There's some related renovate config which should be removed along with this change. Currently we block 3.x updates from renovate, but we'd (presumably) like to allow them once we've made it to v3. (We might want to unblock the `react` updates as well?)

**Comment by jgarrow** [comment]
> There's some related renovate config which should be removed along with this change. Currently we block 3.x updates from renovate, but we'd (presumably) like to allow them once we've made it to v3. (We might want to unblock the `react` updates as well?)

@trevor-scheer ooh yes, we'll want to allow 3.x updates once this is merged in. For `react` updates, this version will still be on v16, so perhaps leave those off? @trevorblades does this sound reasonable to you?

**Comment by trevorblades** [comment]
Yup sounds good to me @jgarrow

**Pull request merged**
