### PR TITLE
chore(deps): Update `graphql` and related dependencies

### PR DESCRIPTION
**Pull request by trevor-scheer**

### CODE REVIEW

**Comment by trevor-scheer** [comment]
Is there any reason we'd want to continue supporting `graphql@14.x` or really anything besides more cutting edge versions for Fed 2? Can we get to 16+ before launch?

I'd like to get gateway supporting v16 asap, this seems like a good first step. Unfortunately there's a minor version bump in `graphql-js` which breaks `@apollo/core-schema@0.1.0`. The fix requires getting peer deps up to `^15.7.x`.
Ref: https://github.com/apollographql/core-schema-js/pull/20

**Comment by clenfest** [comment]
I'm not qualified to judge the Rust stuff, but if it compiles, it's probably fine, right? Otherwise LGTM.

**Comment by trevor-scheer** [comment]
@clenfest fortunately the Rust stuff is just cherry-picked from the `version-0.x` branch PR which addresses this same issue #1149

**Review by clenfest — APPROVED** [review]
Approving since Rust changes are approved already in #1149

**Comment by trevor-scheer** [comment]
Leaving this for @pcmanus or @martijnwalraven to merge

**Review by pcmanus — APPROVED** [review]
Lgtm as well.

**Pull request merged**
