### PR TITLE
Update apollo-server dependencies

### PR DESCRIPTION
**Pull request by trevor-scheer**
Apollo Server just published `v2.19.0`
Ref: https://github.com/apollographql/apollo-server/pull/4626

I'll follow up landing this PR with a patch release for the gateway.

### CODE REVIEW

**Review by Enrico2 — APPROVED** [review]
next week release sounds good.

**Comment by ashleygwilliams** [comment]
failing on code coverage, rerunning to see if a fluke

**Review by cabelitos — APPROVED** [review]
LGTM. Please could we have a release with this one? It's impacting us.

**Comment by abernix** [comment]
This was released!

**Pull request merged**
