### PR TITLE
Release @apollo/gateway@0.26.0, @apollo/federation@0.23.0

### PR DESCRIPTION
**Pull request by trevor-scheer**
As with release PRs in the past, this is a PR tracking a release-x.y.z branch for an upcoming release of Apollo Federation and Gateway. 🙌 The version in the title of this PR should correspond to the appropriate branch.

Check the appropriate milestone (to the right) for more details on what we hope to get into this release!

The intention of these release branches is to gather changes which are intended to land in a specific version (again, indiciated by the subject of this PR). Release branches allow additional clarity into what is being staged, provide a forum for comments from the community pertaining to the release's stability, and to facilitate the creation of pre-releases (e.g. alpha, beta, rc) without affecting the master branch.

PRs for new features might be opened against or re-targeted to this branch by the project maintainers. The master branch may be periodically merged into this branch up until the point in time that this branch is being prepared for release. Depending on the size of the release, this may be once it reaches RC (release candidate) stage with an -rc.x release suffix. Some less substantial releases may be short-lived and may never have pre-release versions.

When this version is officially released onto the latest npm tag, this PR will be merged into main.

### CODE REVIEW

**Comment by trevor-scheer** [comment]
More `macos` failures and just on the release commit which bumps version #s! 😞

**Comment by trevor-scheer** [comment]
^^ `macos` stuff was passing on the PR (#626), which subsequently failed CI upon landing in this branch. Are caches per branch?

**Comment by abernix** [comment]
@trevor-scheer Caches are scoped on the cache key _and branch_, according to: https://github.com/actions/cache#cache-scopes

**Comment by trevor-scheer** [comment]
Admin merging because of known `macos` failures occurring seemingly on this branch only.

**Pull request merged**
