### PR TITLE
docs: fed versions

### PR DESCRIPTION
**Pull request by shorgi**
Fix spacing and line breaks for Fed versions page

### CODE REVIEW

**Review by Meschreiber — COMMENTED** [review]
I wonder if there's a way to add spacing but keep things horizontal? (I feel like using an extra line break might not be necessary?)

**Comment by shorgi** [comment]
> I wonder if there's a way to add spacing but keep things horizontal? (I feel like using an extra line break might not be necessary?)

I think this has been vertical all along? (Can't prove it with both old docs and wayback machine down ...)

**Comment by Meschreiber** [comment]
> > I wonder if there's a way to add spacing but keep things horizontal? (I feel like using an extra line break might not be necessary?)
> 
> I think this has been vertical all along? (Can't prove it with both old docs and wayback machine down ...)

I mean the `First release: Date` vs `First release /n date

Current: 
image

This PR:
image

**Comment by shorgi** [comment]
>
> I mean the `First release: Date` vs `First release /n date`
> 

ah, I meant that having the `/n` was what was there before in the old docs. (And there wasn't any period or colon after First release or Minimum router version. they were already on separate lines)

**Comment by Meschreiber** [comment]
Got it. I have a preference for the horizontal version since it seems more natural/space-efficient for me, but I'm fine with whatever you decide!

**Review by Meschreiber — APPROVED** [review]

**Pull request merged**
