### PR TITLE
Release @apollo/federation 0.21.3 (and @apollo/gateway 0.23.3)

### LINKED ISSUE #537: [@apollo/federation 0.21.2] types.d.ts uses GraphQLObjectType with 3 instead 2 type parameters
Hi! I just added `@apollo/federation 0.21.2` as a dependency in my project and get the following TS error:

```ts
node_modules/@apollo/federation/dist/types.d.ts:3:35 - error TS2707: Generic type 'GraphQLObjectType<TSource, TContext>' requires between 0 and 2 type arguments.

3 export declare const ServiceType: GraphQLObjectType<any, any, {
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4     [key: string]: any;
  ~~~~~~~~~~~~~~~~~~~~~~~
5 }>;
  ~~
```

I checked out [@apollo/federation master](https://github.com/apollographql/federation) and ran `npm run compile` with an additional compiler option `"declaration": true` in `tsconfig.build.json` an this results in a correct `dist/types.d.ts`:

```ts
import { GraphQLFieldConfig, GraphQLUnionType, GraphQLObjectType, GraphQLScalarType, GraphQLType, GraphQLNamedType, GraphQLResolveInfo } from 'graphql';
export declare const EntityType: GraphQLUnionType;
export declare const ServiceType: GraphQLObjectType<any, any>; // <-- ONLY 2 TYPE PARAMETERS
export declare const AnyType: GraphQLScalarType;
export declare type GraphQLReferenceResolver<TContext> = (reference: object, context: TContext, info: GraphQLResolveInfo) => any;
declare module 'graphql/type/definition' {
    interface GraphQLObjectType {
        resolveReference?: GraphQLReferenceResolver<any>;
    }
    interface GraphQLObjectTypeConfig<TSource, TContext> {
        resolveReference?: GraphQLReferenceResolver<TContext>;
    }
}
export declare const entitiesField: GraphQLFieldConfig<any, any>;
export declare const serviceField: GraphQLFieldConfig<any, any>;
export declare const federationTypes: GraphQLNamedType[];
export declare function isFederationType(type: GraphQLType): boolean;
//# sourceMappingURL=types.d.ts.map
```

**Other Dependencies in the Project**

```json
"typescript": "^4.2.2",
"graphql": "^15.5.0",
"apollo-server-core": "^2.21.0",
```

### PR DESCRIPTION
**Pull request by glasser**
This is the release PR for @apollo/federation 0.21.3. It is a cherry-pick that resolves #537 by building output that is compatible with graphql@15.

### CODE REVIEW

**Review by trevor-scheer — APPROVED** [review]
Based on comment here, this looks correct to me:
https://github.com/apollographql/federation/issues/537#issuecomment-791588570

**Comment by glasser** [comment]
While the problem in #537 makes sense to me, I wasn't able to easily directly reproduce on my machine so I can't confirm this alpha fixes. I'll release this as non-alpha once somebody who can reproduce the problem (such as @schulzp) tells me this fixes it!

**Comment by abernix** [comment]
@schulzp: Any updates on @glasser's ask above?

**Comment by abernix** [comment]
Just in case it's not clear, the alphas are available for testing in these package names:

```
 - @apollo/federation@0.21.3-alpha.0
 - @apollo/gateway@0.23.3-alpha.0
```

**Comment by glasser** [comment]
We didn't release this patch release because we didn't get confirmation that it fixed the issue for @schulzp. However, the fix was released in `@apollo/federation@v0.22.0` anyway, so this patch release shouldn't be necessary anymore (unless for some reason it turns out there are people who need this fix who are unable to upgrade to v0.22 (which has no intentional breaking changes).

**Pull request closed without merging**
