### PR TITLE
Add scrolling style to too-large error tables

### PR DESCRIPTION
**Pull request by StephenBarlow**

### CODE REVIEW

**Review by cpeacock — APPROVED** [review]

**Comment by StephenBarlow** [comment]
@pcmanus I've made this change the wrong way, editing the article's output instead of the source template. Being a bit of a TypeScript newbie, I'm not figuring out the right way to modify the `.ts` template with these changes and then compile them out so they run properly in CI. Could you take a look at this when you have a chance?

This just makes sure the error code table doesn't extend arbitrarily far out beyond the bounds of the article.

**Review by trevor-scheer — APPROVED** [review]

**Comment by StephenBarlow** [comment]
@benweatherman I pushed up some tweaks to the hints article template and would love one last sanity check before merge whenever's convenient! https://github.com/apollographql/federation/pull/1740/commits/fe34baadfc135437d1254a9958ed78aab2d2051f

**Review by benweatherman — APPROVED** [review]
🐐 This is great! Thanks for code golfing with us.

Lemme know if you want me to merge this or if you wanna do the needful.

**Comment by StephenBarlow** [comment]
Woo thanks all! Merged 😎

**Pull request merged**
