### PR TITLE
Remove `node` types from `@apollo/composition` tsconfig

### PR DESCRIPTION
**Pull request by trevor-scheer**
The `@apollo/composition` library is also compiled for `rover`, to be used in deno where the Node API is unavailable. To prevent accidental usage of Node builtins, this removes the typically-available `node` types from the `tsconfig.json` of this package in particular.

For example, `console` is no longer available globally. Packages like `crypto` and `util` (among many Node standard libs) are also no longer available and their use will result in TS errors.

These errors may be surprising to a developer. This constraint isn't something most people keep at the forefront of their mind (which is why I think this change is very helpful in preventing a future problem). Any feedback on how to document this well would be very welcome!

### CODE REVIEW

**Comment by pcmanus** [comment]
> For example, `console` is no longer available

😭 . How am I supposed to debug stuffs now ?!@#

Some kidding aside, I know that I will need a simple way to disable this for when debugging, and while I can probably work something locally on my end, that might be something more generally and I'd appreciate adding something here.

Also, `@apollo/composition` depends on other packages, isn't it a concern for those too? I'm thinking of `@apollo/federation-internals` in particular, which include some specific baked-in debugging capability that rely on `console` (and _are_ used by composition, though only when you setup some specific env variable).

**Comment by trevor-scheer** [comment]
Good points @pcmanus. I suspect there's a good way to:
* Pinpoint / target _only_ files used by `rover`
* Continue to allow things that are already polyfilled by `rover` (like `console`!)

And yes, not pulling in `query-graphs` and `federation-internals` is an oversight (and really makes the bullets above more important since the other packages do need to follow these rules as well, so limiting the impact is even more preferable).

Going to mark this as WIP. I welcome anyone who feels nerd-sniped to collaborate on this problem with me, else I might get to it in some free time if I feel inspired. I don't think there's any immediate concern here.

A couple other things:
* `// @ts-ignore` would suffice for debugging (though less ergonomic, a snippet would be handy for this)
* Happy to share an ergonomic step debugging approach with you (if you're in VS Code for TS development). It's fantastic, I usually just skip console debugging altogether now.

**Comment by abernix** [comment]
I agree that `// @ts-ignore` and native debugging integrations could be viable paths here.  As another option, if `console` is the biggest point of contention, we could just add a local `global` TS declaration that itself declares the `Console` types in the way that they are compatible with our usage of them.

Basically, we could copy this and whittle it down to what we need:

- [The `Console` from the `dom` libs](https://github.com/microsoft/TypeScript/blob/15f7b6f68791487c059d41d5fe99117f79e1f1a2/lib/lib.dom.d.ts#L17727-L17748)
- [Something like what `@types/node` does](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/console.d.ts#L58-L61)

Overall, this still solves what could be an eventual "surprise" factor in our release pipeline between `federation` and `rover` so the consideration is still viable and I think this was a creative solution.  It could also be solved with linting or something.

That said, there is a lot of other stuff to do right now so if the team is at least conscious of their usage of Node.js standard lib usage and actively avoids introducing that in their implementations and reviews of those implementations, I don't think this is urgent.

I'm going to (finally) remove myself as a reviewer on this because I get pinged on it every day, but those are my thoughts.  Happy to discuss.

**Comment by trevor-scheer** [comment]
@abernix agree re: urgency and I appreciate the alternatives! I've removed the others as reviewers as well. I'll leave this open since I think there are some good options here and I do still think this potential pitfall should be patched up. I won't be tackling this though, so I'll leave it to the team to decide on the future of this (closing is fine by me if that's the eventual decision).

**Comment by trevor-scheer** [comment]
Closing in favor of a more thorough approach theorized in https://github.com/apollographql/federation/issues/2453

**Pull request closed without merging**
