### PR TITLE
Minor edits to fed2 error code doc generation

### PR DESCRIPTION
**Pull request by StephenBarlow**
The error reference auto-generation is a great plan! These are just small copyedits to the template.

### CODE REVIEW

**Review by pcmanus — APPROVED** [review]
You'll need to run the generation and include it in the PR for the new CI check to be happy, but looks good to me otherwise, thanks.

**Comment by StephenBarlow** [comment]
Ahh whoops I did that and pushed the updated branch to the wrong remote 🤦 thanks I'll get this sorted

**Comment by benweatherman** [comment]
@StephenBarlow Hope it's OK to revive this PR! I also brought a change over to the new hints generation script. Wanna squash and merge this when the checks pass?

**Comment by StephenBarlow** [comment]
Ah yeah sure, forgot about this! Thanks 😄

**Pull request merged**
