### PR TITLE
chore: Update graphql rule imports to support graphql@16 users (version-0.x)

### PR DESCRIPTION
**Pull request by trevor-scheer**
Fixes https://github.com/apollographql/federation/issues/1175

### CODE REVIEW

**Review by pcmanus — APPROVED** [review]
I'm not the best expert on graphql-js around here but I'm decently confident this is the proper fix indeed. +1 from me.

**Review by IvanGoncharov — APPROVED** [review]
Correct 👍 
BTW, we need to add a better mechanism to omit rules in `graphql-js`, just something to think about.

**Review by clenfest — APPROVED** [review]
lgtm

**Comment by williamrijksen** [comment]
When is this PR scheduled for release?

**Comment by pcmanus** [comment]
> When is this PR scheduled for release?

I believe that was part of gateway release 0.44.0 that was released a few days ago (we even just had the 0.44.1 release). See https://www.npmjs.com/package/@apollo/gateway.

**Comment by trevor-scheer** [comment]
@williamrijksen Note this is not the PR to officially introduce support for `graphql@16`. This is a step towards it. Apologies if the title is misleading.

**Comment by williamrijksen** [comment]
@trevor-scheer where can I find a checklist with the things which are required to support graphql16?

**Comment by trevor-scheer** [comment]
@williamrijksen I'm not sure what you mean. Supported by the federation projects or an end-user project?

There's a renovate PR to update the graphql version here: https://github.com/apollographql/federation/pull/1130 which is currently failing based on a couple failing dependencies. Once we address those and make sure CI is passing we can land that upgrade. I currently have a PR open to one of the failing deps (https://github.com/apollographql/core-schema-js/pull/19) to add v16 support.

**Pull request merged**
