### PR TITLE
Update OTel-JS broken link

### PR DESCRIPTION
**Pull request by MannyPamintuanAtCare**
This PR does the following,

Updates the link to "Getting Started" to the [most recent link provided in the OTel-JS Repo](https://github.com/open-telemetry/opentelemetry-js/blob/main/README.md?plain=1#L5)

This change in linking is documented in OTel-JS [commit #2493](https://github.com/open-telemetry/opentelemetry-js/pull/2493)

### CODE REVIEW

**Comment by MannyPamintuanAtCare** [comment]
🚀 ✨ 🌕 
Making the world a better place, one less broken link at a time.

**Review by abernix — APPROVED** [review]
Thank you for your 🌍 -improving! LGTM.

(If you wanted to also do this on the `main` branch, that'd be much appreciated, but I can follow-up myself if not. 😉 )

**Comment by MannyPamintuanAtCare** [comment]
> Thank you for your 🌍 -improving hyperlink-awareness! LGTM.
> 
> (If you wanted to also do this on the `main` branch, that'd be much appreciated, but I can follow-up myself if not. 😉 )

You're most welcome, Jesse!
I am more than happy to put in a PR for the `main` branch as well and [have done so](https://github.com/apollographql/federation/pull/1303), ready for review at y'alls convenience. :)

**Comment by abernix** [comment]
Thanks!

**Pull request merged**
