### PR TITLE
Specify which role for API key

### PR DESCRIPTION
**Pull request by kdawgwilk**
I dont know if this is accurate but I could not find the answer to the question "which role does the API key need to have for a gateway using managed federation

### CODE REVIEW

**Comment by kdawgwilk** [comment]
Anything I can do to get this merged?

**Comment by pcmanus** [comment]
@StephenBarlow could have a quick look at this one? It seems pretty easy, but I'm a bit unfamiliar with studio roles and API keys so I'd rather let double check.

@kdawgwilk really sorry about this, the delay is a bit embarrassing. I think this felt through the cracks. Let's try to get that in sorted.

**Comment by StephenBarlow** [comment]
Ah yes thanks for the PR! I did indeed let this fall through the cracks. CI is unhappy with this PR at the moment, but I can hopefully get this sorted tomorrow.

**Review by StephenBarlow — APPROVED** [review]

**Comment by kdawgwilk** [comment]
let me know if this change is still okay to merge or I can close it out

**Comment by StephenBarlow** [comment]
Merged! Thanks @kdawgwilk

**Pull request merged**
